import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

import { interpretDesktopInstruction } from "../desktop/approval-rules.js";

test("interpretDesktopInstruction mirrors V1 send and ignore rules", () => {
  assert.deepEqual(interpretDesktopInstruction("发吧"), { action: "send" });
  assert.deepEqual(interpretDesktopInstruction("忽略"), { action: "ignore" });
  assert.deepEqual(interpretDesktopInstruction("语气软一点"), {
    action: "rewrite",
    instruction: "语气软一点"
  });
  assert.deepEqual(interpretDesktopInstruction("  "), { action: "empty" });
});

test("desktop generated instruction rules match the backend canonical rules", () => {
  const backend = readFileSync(new URL("../src/approval/instruction-rules.js", import.meta.url), "utf8");
  const frontend = readFileSync(new URL("../desktop/instruction-rules.generated.js", import.meta.url), "utf8");

  assert.equal(frontend, `// Generated by scripts/sync-desktop-rules.js. Do not edit by hand.\n${backend}`);
});
