export const STATUS = Object.freeze({
  RECEIVED: "RECEIVED",
  DRAFTED: "DRAFTED",
  PENDING_APPROVAL: "PENDING_APPROVAL",
  APPROVED: "APPROVED",
  SENT: "SENT",
  IGNORED: "IGNORED",
  REJECTED: "REJECTED",
  REWRITE_REQUIRED: "REWRITE_REQUIRED",
  DIRECTION_REQUIRED: "DIRECTION_REQUIRED",
  MEETING_REQUESTED: "MEETING_REQUESTED",
  SEND_FAILED: "SEND_FAILED",
  DRAFT_FAILED: "DRAFT_FAILED",
  SUPERSEDED: "SUPERSEDED"
});
